# Generated by Django 5.2.7 on 2025-11-12 01:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_time", models.TimeField(blank=True, null=True)),
                ("profile_text", models.TextField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("hobbies", models.JSONField(blank=True, default=list)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                ("photos", models.JSONField(blank=True, default=list)),
                (
                    "mbti",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MBTI는 대문자 4글자여야 합니다.",
                                regex="^[A-Z]{4}$",
                            )
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
