# Generated by Django 5.2.8 on 2025-12-07 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('birth_time_unknown', models.BooleanField(default=False)),
                ('hobbies', models.JSONField(blank=True, null=True)),
                ('mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('location_city', models.CharField(blank=True, max_length=50, null=True)),
                ('location_district', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('profile_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', '스팸'), ('ABUSE', '욕설 및 비하 발언'), ('ADULT', '나체 이미지 및 성적 행위'), ('FAKE', '사기 및 거짓')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PROFILE', '프로필'), ('CHAT', '채팅방')], default='PROFILE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '접수 대기'), ('RESOLVED', '처리 완료'), ('REJECTED', '반려됨')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
