# profiles/migrations/0003_remove_userprofile_preferences.py
# Generated by Django 5.2.7 on 2025-11-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_userprofile_bio_userprofile_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="preferences",
        ),
    ]
