# profiles/migrations/0008_userprofile_city_userprofile_district_and_more.py
# Generated by Django 5.2.7 on 2025-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_birth_time_unknown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
