# profiles/migrations/0010_remove_userprofile_city_remove_userprofile_district.py
# Generated by Django 5.2.7 on 2025-11-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
    ]
