# Generated by Django 5.2.8 on 2025-11-29 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_userprofile_city_remove_userprofile_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PROFILE', '프로필'), ('CHAT', '채팅방')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PROFILE', '프로필'), ('CHAT', '채팅방')], default='PROFILE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', '접수 대기'), ('RESOLVED', '처리 완료'), ('REJECTED', '반려됨')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
