# Generated by Django 5.2.8 on 2025-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('SPAM', '스팸'), ('ABUSE', '욕설 및 비하 발언'), ('ADULT', '나체 이미지 및 성적 행위'), ('FAKE', '사기 및 거짓'), ('OTHER', '기타')], max_length=20),
        ),
    ]
