# api/migrations/0004_remove_profileimage_profile_delete_profile_and_more.py
# Generated by Django 5.2.7 on 2025-11-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_birth_time_unknown_profile_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
