# chat/migrations/0004_userprofile_mbti.py
# Generated by Django 5.2.7 on 2025-11-11 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mbti",
            field=models.CharField(
                blank=True,
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="MBTI는 대문자 4글자여야 합니다.", regex="^[A-Z]{4}$"
                    )
                ],
            ),
        ),
    ]
