# chat/migrations/0005_delete_userprofile.py
# Generated by Django 5.2.7 on 2025-11-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_userprofile_mbti"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
